resources:
  containers:
  - container: mysql8
    image: mattcooper/python-mysql:latest      

phases:
# - template: steps.yml
#   parameters:
#     name: Linux
#     queue: Hosted Linux Preview
#     platform: Linux

# - template: steps.yml
#   parameters:
#     name: Windows
#     queue: Hosted VS2017
#     platform: Windows
#
- template: container.yml
  parameters:
    name: MySQL
    container: mysql8
    start_script: .vsts/start_mysql.sh
    extra_requirements_file: mysql.txt
