phases:
# - template: steps.yml
#   parameters:
#     name: Linux
#     queue: Hosted Linux Preview
#     platform: Linux

# - template: steps.yml
#   parameters:
#     name: Windows
#     queue: Hosted VS2017
#     platform: Windows

- template: mysql.yml
  