resources:
  containers:
  - container: mysql8
    image: mysql:8.0

phases:
# - template: steps.yml
#   parameters:
#     name: Linux
#     queue: Hosted Linux Preview
#     platform: Linux

# - template: steps.yml
#   parameters:
#     name: Windows
#     queue: Hosted VS2017
#     platform: Windows

- template: container.yml
  parameters:
    name: MySQL
    container: mysql8
    env:
      MYSQL_ROOT_PASSWORD: super-secret
